[2023-03-03T21:52:36.796+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sandbox.get_data_nexrad_from_aws manual__2023-03-03T21:52:25.517961+00:00 [queued]>
[2023-03-03T21:52:36.805+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sandbox.get_data_nexrad_from_aws manual__2023-03-03T21:52:25.517961+00:00 [queued]>
[2023-03-03T21:52:36.806+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T21:52:36.807+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-03T21:52:36.807+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T21:52:36.820+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_data_nexrad_from_aws> on 2023-03-03 21:52:25.517961+00:00
[2023-03-03T21:52:36.845+0000] {standard_task_runner.py:55} INFO - Started process 11360 to run task
[2023-03-03T21:52:36.859+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sandbox', 'get_data_nexrad_from_aws', 'manual__2023-03-03T21:52:25.517961+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/noaa.py', '--cfg-path', '/tmp/tmppcc1vbs7']
[2023-03-03T21:52:36.861+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask get_data_nexrad_from_aws
[2023-03-03T21:52:37.008+0000] {task_command.py:388} INFO - Running <TaskInstance: sandbox.get_data_nexrad_from_aws manual__2023-03-03T21:52:25.517961+00:00 [running]> on host a1445a4c94cf
[2023-03-03T21:52:37.147+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sandbox
AIRFLOW_CTX_TASK_ID=get_data_nexrad_from_aws
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T21:52:25.517961+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-03T21:52:25.517961+00:00
[2023-03-03T21:52:37.149+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_all_nexrad_file_name_by_filter_new() missing 1 required positional argument: 'year'
[2023-03-03T21:52:37.164+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=sandbox, task_id=get_data_nexrad_from_aws, execution_date=20230303T215225, start_date=20230303T215236, end_date=20230303T215237
[2023-03-03T21:52:37.195+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 28 for task get_data_nexrad_from_aws (get_all_nexrad_file_name_by_filter_new() missing 1 required positional argument: 'year'; 11360)
[2023-03-03T21:52:37.238+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-03T21:52:37.261+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
