[2023-03-03T21:16:57.716+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sandbox.get_data_goes_from_aws manual__2023-03-03T21:16:54.063026+00:00 [queued]>
[2023-03-03T21:16:57.722+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sandbox.get_data_goes_from_aws manual__2023-03-03T21:16:54.063026+00:00 [queued]>
[2023-03-03T21:16:57.723+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T21:16:57.724+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-03T21:16:57.724+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T21:16:57.733+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_data_goes_from_aws> on 2023-03-03 21:16:54.063026+00:00
[2023-03-03T21:16:57.747+0000] {standard_task_runner.py:55} INFO - Started process 9524 to run task
[2023-03-03T21:16:57.756+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sandbox', 'get_data_goes_from_aws', 'manual__2023-03-03T21:16:54.063026+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/noaa.py', '--cfg-path', '/tmp/tmpdcrbpv1z']
[2023-03-03T21:16:57.760+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask get_data_goes_from_aws
[2023-03-03T21:16:57.834+0000] {task_command.py:388} INFO - Running <TaskInstance: sandbox.get_data_goes_from_aws manual__2023-03-03T21:16:54.063026+00:00 [running]> on host a1445a4c94cf
[2023-03-03T21:16:58.551+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sandbox
AIRFLOW_CTX_TASK_ID=get_data_goes_from_aws
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T21:16:54.063026+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-03T21:16:54.063026+00:00
[2023-03-03T21:16:58.591+0000] {logging_mixin.py:137} INFO - ********************** get_all_geos_file_name_by_filter_new****************
[2023-03-03T21:17:00.593+0000] {logging_mixin.py:137} INFO - get_aws_details_by_filename
[2023-03-03T21:17:00.606+0000] {logging_mixin.py:137} INFO - insert
[2023-03-03T21:17:00.612+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 68, in get_all_geos_file_name_by_filter_new
    metadata.insert_data_into_goes(station=station_id, year=year, day_of_year=day, hour=hour, filename=file_name)
  File "/opt/airflow/dags/postgres_db_script.py", line 48, in insert_data_into_goes
    insert_str = 'INSERT INTO '+ self.table_name_goes+ '(station, year, day_of_year, hour, filename) VALUES(' + station +','+ year +','+day_of_year+','+hour+','+filename+');'
TypeError: can only concatenate str (not "int") to str
[2023-03-03T21:17:02.891+0000] {local_task_job.py:208} INFO - Task exited with return code Negsignal.SIGKILL
[2023-03-03T21:17:02.928+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
